### ISSUE TITLE
llama 3.1 405B -> Output it not Correct Markdown

### ISSUE THREAD

**Issue by actswartz** [chathub-dev/chathub#1260]
Paid Customer ...

llama 3.1 405b 
try:  list the first 5 us presidents

then cop the output and paste to https://stackedit.io/app#

Which is not good markup and looks horrible....

**Comment by wong2** [comment]
I think the problem is how stackedit handles paste by default, if you paste with this option, it works fine:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/21a1d135-1a1e-4bc1-a5e5-d5db472558dc">


I've tested with several other Markdown preview service, and they work well by default.
https://markdownlivepreview.com/
https://dillinger.io/
